// GENERATED by tools/measure-figure-type.mjs (S3 PR-A task A2a) — DO NOT
// HAND-EDIT. Regenerate with `node tools/measure-figure-type.mjs
// docs/design-labs/s3-figures`. Source of truth is
// docs/design-labs/s3-figures/measured-figure-type.json, written by that rig
// run against a real headless-Edge render, after waiting on
// `document.fonts.ready` and confirming JetBrains Mono (not a fallback face)
// resolved.
export interface MeasuredFigureType {
  /** Advance width, in CSS px, of one JetBrains Mono char at 11px + .08em
   * letter-spacing (mean over a 40-char run). */
  monoChPx: number;
  /** getBoundingClientRect().width of a `width: max-content`,
   * box-sizing:border-box node box holding the literal "ORCHESTRATOR" (12
   * chars, the longest single word in the registry) with the node's real
   * `9px 10px` padding already included. */
  nodeMinPx: number;
  /** The figure container's own content-box width (ResizeObserver.contentRect
   * domain) at a 320px viewport, driven through the real CaseStudyPage
   * padding chain. */
  narrowestContentPx: number;
  /** Which box each measurement above is expressed in. */
  observedBox: "content" | "border";
  /** The font family that actually resolved when measuring (guards against
   * recording a fallback monospace face under `display=swap`). */
  resolvedFontFamily: string;
}

export const MEASURED_FIGURE_TYPE: MeasuredFigureType = {
  monoChPx: 7.480078125,
  nodeMinPx: 109.765625,
  narrowestContentPx: 238,
  observedBox: "content",
  resolvedFontFamily: "JetBrains Mono",
};
