// GENERATED by tools/measure-battle-layout.mjs (M7 PR-B task B1/B2, extended
// by M12 PR-B task B2) — DO NOT HAND-EDIT. Regenerate with
// `npm run measure:layout`. Source of truth is
// docs/battle-prototypes/m12-menu/measured.json, written by the same rig run
// (the rig's output root is per-milestone as of M12 PR-B task B4 — the M7
// baseline captures/measured.json remain frozen under m7-clip/).
// Every row here comes from a real headless-Edge measurement at the
// corresponding viewport (see that file for the full raw data, including
// viewport-relative rects this module omits).
export interface LevelMeasure {
  /** Max rendered panel height (CSS px) across every cursor position within
   * this level (M12 plan PR-B task B2, owner-ruled amendment: the footer
   * renders the active row's description, and long ones wrap to a second
   * line, so panel height is cursor-dependent — only walking every row and
   * keeping the max reports the true worst case). */
  panelHeight: number;
  /** True if body.scrollHeight > body.clientHeight at ANY walked cursor
   * position within this level. */
  scrollable: boolean;
}

export interface MeasuredLayoutRow {
  vw: number;
  vh: number;
  isMobile: boolean;
  /** [data-battle]'s own rendered height in CSS px (the B1 finding: compare
   * against vh — see measured.json's containerEqualsVh per row). */
  containerHeight: number;
  /** The COMMAND panel's rendered height in CSS px — the MAX over the three
   * levels' own `levels.*.panelHeight` (M12 plan PR-B task B2 item 3; the
   * clip invariant consumes this worst case unchanged). An input, not
   * derivable; see layout.ts's commandPanelRect doc comment. */
  panelHeight: number;
  /** The <canvas> rect, CONTAINER-relative (matches layout.ts's own
   * coordinate system, not viewport-relative getBoundingClientRect()). */
  canvasRect: { left: number; top: number; width: number; height: number };
  /** Per-level worst-case measurement (M12 plan PR-B task B2). */
  levels: { top: LevelMeasure; skills: LevelMeasure; spells: LevelMeasure };
}

export const MEASURED_LAYOUT: readonly MeasuredLayoutRow[] = [
  { vw: 1920, vh: 1080, isMobile: false, containerHeight: 1080, panelHeight: 205, canvasRect: {"left":320,"top":104.390625,"width":1280,"height":720}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1600, vh: 900, isMobile: false, containerHeight: 900, panelHeight: 205, canvasRect: {"left":224,"top":63,"width":1152,"height":648}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1440, vh: 900, isMobile: false, containerHeight: 900, panelHeight: 205, canvasRect: {"left":144,"top":63,"width":1152,"height":648}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1440, vh: 720, isMobile: false, containerHeight: 720, panelHeight: 205, canvasRect: {"left":272,"top":57.59375,"width":896,"height":504}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1280, vh: 800, isMobile: false, containerHeight: 800, panelHeight: 205, canvasRect: {"left":128,"top":56,"width":1024,"height":576}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1280, vh: 620, isMobile: false, containerHeight: 620, panelHeight: 205, canvasRect: {"left":256,"top":50.59375,"width":768,"height":432}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 1024, vh: 768, isMobile: false, containerHeight: 768, panelHeight: 205, canvasRect: {"left":64,"top":78.234375,"width":896,"height":504}, levels: { top: { panelHeight: 162, scrollable: false }, skills: { panelHeight: 174, scrollable: false }, spells: { panelHeight: 205, scrollable: false } } },
  { vw: 800, vh: 600, isMobile: false, containerHeight: 600, panelHeight: 148, canvasRect: {"left":16,"top":42,"width":768,"height":432}, levels: { top: { panelHeight: 148, scrollable: true }, skills: { panelHeight: 148, scrollable: true }, spells: { panelHeight: 148, scrollable: true } } },
  { vw: 759, vh: 900, isMobile: true, containerHeight: 900, panelHeight: 242, canvasRect: {"left":0,"top":151.375,"width":759,"height":426.9375}, levels: { top: { panelHeight: 202, scrollable: false }, skills: { panelHeight: 202, scrollable: false }, spells: { panelHeight: 242, scrollable: false } } },
  { vw: 430, vh: 932, isMobile: true, containerHeight: 932, panelHeight: 242, canvasRect: {"left":0,"top":220.828125,"width":430,"height":241.875}, levels: { top: { panelHeight: 202, scrollable: false }, skills: { panelHeight: 202, scrollable: false }, spells: { panelHeight: 242, scrollable: false } } },
  { vw: 390, vh: 844, isMobile: true, containerHeight: 844, panelHeight: 242, canvasRect: {"left":0,"top":199.875,"width":390,"height":219.375}, levels: { top: { panelHeight: 202, scrollable: false }, skills: { panelHeight: 215, scrollable: false }, spells: { panelHeight: 242, scrollable: false } } },
  { vw: 360, vh: 640, isMobile: true, containerHeight: 640, panelHeight: 255, canvasRect: {"left":0,"top":140,"width":360,"height":202.5}, levels: { top: { panelHeight: 202, scrollable: false }, skills: { panelHeight: 215, scrollable: false }, spells: { panelHeight: 255, scrollable: false } } },
];
