// Canon extractor (BUILDING.md §8: locked assets are extracted verbatim, never retyped).
//
// Sources of truth:
//   docs/battle-prototypes/station-glass.html  — the LOCKED station v1 canon (spec 2026-07-27)
//
// Transform contract (re-runnable byte-for-byte; verify mode re-runs it and diffs):
//   1. Take the single <script> block of station-glass.html.
//   2. Strip the two trailing DOM writes (everything from the line containing
//      `document.getElementById('station')` onward).
//   3. Wrap the remaining body — verbatim, untouched — as
//      `buildStationCanon(idSuffix = ""): string`, appending the id-suffix rename
//      (fcL/skL/wtL, needed when two station copies share one document) and a full
//      <svg viewBox="-510 -510 1020 1020"> return wrapper.
//   4. Emit src/generated/stationCanon.js under a generated header ("verbatim"
//      means verbatim BELOW the header; strict tsconfig cannot compile the lab JS,
//      so the module is .js with a hand-written .d.ts).
//
// Drift guard (3-copy problem): dive-intro.html embeds its own hand-wrapped copy of
// the station builder (`buildStationString`). Verify mode also normalizes that body
// and diffs it against the canon body, so the lab copy cannot drift silently.
//
// Usage:  node tools/extract-canon.mjs           (regenerate)
//         node tools/extract-canon.mjs --verify  (diff only; exit 1 on drift)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STATION_LAB = resolve(root, "docs/battle-prototypes/station-glass.html");
const DIVE_LAB = resolve(root, "docs/battle-prototypes/dive-intro.html");
const OUT_JS = resolve(root, "src/generated/stationCanon.js");
const OUT_TIMELINE = resolve(root, "src/generated/diveTimeline.js");

// Every symbol the dive lab's pure block declares — all exported, no cherry-picking.
const TIMELINE_EXPORTS = [
  "PAL", "SPR_HERO", "STAGE_W", "STAGE_H", "SCX", "SCY",
  "T_CUT", "FLIP0", "FLIP1", "T_TOUCH", "RV0", "RV1", "RV_MAX",
  "RIP_START", "RIP_DUR", "B0", "B1", "BFL", "NB",
  "T_MENU", "MENU_DUR", "T_END", "LAND_S", "FALL_S",
  "clamp01", "easeOut", "easeIO", "birdParam", "computeState",
];

function fail(msg) {
  console.error("extract-canon: " + msg);
  process.exit(1);
}

// Windows checkouts may be CRLF; the transform is defined over LF content.
function readLf(path) {
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

function extractStationBody() {
  const html = readLf(STATION_LAB);
  const m = html.match(/<script>\n([\s\S]*?)<\/script>/);
  if (!m) fail("no <script> block found in station-glass.html");
  const body = m[1];
  const cut = body.indexOf("document.getElementById('station')");
  if (cut < 0) fail("trailing DOM-write anchor not found in station-glass.html");
  return body.slice(0, cut).replace(/\s+$/, "");
}

function buildModule(body) {
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by tools/extract-canon.mjs from docs/battle-prototypes/station-glass.html
// (station v1 canon, LOCKED 2026-07-27 — spec docs/superpowers/specs/2026-07-27-station-glass-design.md).
// DO NOT EDIT. The canon body below this header is verbatim (BUILDING.md §8).
// Regenerate: node tools/extract-canon.mjs   Verify: npm run verify:canon
export function buildStationCanon(idSuffix = "") {
${body}
if (idSuffix) out = out.replace(/fcL|skL|wtL/g, (t) => t + idSuffix);
return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-510 -510 1020 1020" width="100%" height="100%">' + out + "</svg>";
}
`;
}

// Normalize a builder body for the lab-copy drift diff: strip blank lines and
// trailing whitespace so wrapper-shape differences (function vs top-level) don't
// mask or fake real drift.
function normalize(s) {
  return s
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .filter((l) => l !== "")
    .join("\n");
}

function extractDiveStationBody() {
  const html = readLf(DIVE_LAB);
  const m = html.match(/function buildStationString\(\)\{\n([\s\S]*?)\nreturn out;\n\}/);
  if (!m) fail("buildStationString not found in dive-intro.html");
  return m[1];
}

function extractTimelineBody() {
  const html = readLf(DIVE_LAB);
  const m = html.match(/<script id="pure">\n([\s\S]*?)<\/script>/);
  if (!m) fail('no <script id="pure"> block found in dive-intro.html');
  return m[1].replace(/\s+$/, "");
}

function buildTimelineModule(tbody) {
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by tools/extract-canon.mjs from docs/battle-prototypes/dive-intro.html
// (<script id="pure"> — the Dive to the Heart pure timeline, approved 2026-07-28,
// spec docs/superpowers/specs/2026-07-28-dive-intro-design.md).
// DO NOT EDIT. The block below this header is verbatim (BUILDING.md §8/§9).
// Regenerate: node tools/extract-canon.mjs   Verify: npm run verify:canon
${tbody}
export { ${TIMELINE_EXPORTS.join(", ")} };
`;
}

const body = extractStationBody();
const generated = buildModule(body);
const timelineBody = extractTimelineBody();
const generatedTimeline = buildTimelineModule(timelineBody);

// Drift guard first — the lab's embedded copy must match canon regardless of mode.
const diveBody = extractDiveStationBody();
if (normalize(diveBody) !== normalize(body)) {
  fail("DRIFT: dive-intro.html's embedded station copy no longer matches station-glass.html canon");
}

if (process.argv.includes("--verify")) {
  const targets = [
    [OUT_JS, generated, "stationCanon.js"],
    [OUT_TIMELINE, generatedTimeline, "diveTimeline.js"],
  ];
  for (const [path, fresh, name] of targets) {
    let committed;
    try {
      committed = readLf(path);
    } catch {
      fail("src/generated/" + name + " missing — run: node tools/extract-canon.mjs");
    }
    if (committed !== fresh) fail("DRIFT: committed " + name + " differs from a fresh extraction");
  }
  console.log("verify:canon OK — station + timeline modules match canon; lab station copy matches canon");
} else {
  mkdirSync(dirname(OUT_JS), { recursive: true });
  writeFileSync(OUT_JS, generated);
  writeFileSync(OUT_TIMELINE, generatedTimeline);
  console.log("extract-canon: wrote stationCanon.js (" + generated.length + " b) + diveTimeline.js (" + generatedTimeline.length + " b)");
}
