// Canon extractor (BUILDING.md §8: locked assets are extracted verbatim, never retyped).
//
// Sources of truth:
//   docs/battle-prototypes/station-glass.html  — the LOCKED station v1 canon (spec 2026-07-27)
//
// Transform contract (re-runnable byte-for-byte; verify mode re-runs it and diffs):
//   1. Take the single <script> block of station-glass.html.
//   2. Strip the two trailing DOM writes (everything from the line containing
//      `document.getElementById('station')` onward).
//   3. Wrap the remaining body — verbatim, untouched — as
//      `buildStationCanon(idSuffix = ""): string`, appending the id-suffix rename
//      (fcL/skL/wtL, needed when two station copies share one document) and a full
//      <svg viewBox="-510 -510 1020 1020"> return wrapper.
//   4. Emit src/generated/stationCanon.js under a generated header ("verbatim"
//      means verbatim BELOW the header; strict tsconfig cannot compile the lab JS,
//      so the module is .js with a hand-written .d.ts).
//
// Drift guard (3-copy problem): dive-intro.html embeds its own hand-wrapped copy of
// the station builder (`buildStationString`). Verify mode also normalizes that body
// and diffs it against the canon body, so the lab copy cannot drift silently.
//
// Usage:  node tools/extract-canon.mjs           (regenerate)
//         node tools/extract-canon.mjs --verify  (diff only; exit 1 on drift)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STATION_LAB = resolve(root, "docs/battle-prototypes/station-glass.html");
const DIVE_LAB = resolve(root, "docs/battle-prototypes/dive-intro.html");
const HERO_LAB = resolve(root, "docs/battle-prototypes/hero-battle.html");
const BOSS_LAB = resolve(root, "docs/battle-prototypes/boss-alert-storm.html");
const BF_LAB = resolve(root, "docs/battle-prototypes/battlefield.html");
const OUT_JS = resolve(root, "src/generated/stationCanon.js");
const OUT_TIMELINE = resolve(root, "src/generated/diveTimeline.js");
const OUT_HERO = resolve(root, "src/generated/heroBattle.js");
const OUT_BOSS = resolve(root, "src/generated/bossAlertStorm.js");
const OUT_BF = resolve(root, "src/generated/battlefieldScene.js");

// Every symbol the dive lab's pure block declares — all exported, no cherry-picking.
const TIMELINE_EXPORTS = [
  "PAL", "SPR_HERO", "STAGE_W", "STAGE_H", "SCX", "SCY",
  "T_CUT", "FLIP0", "FLIP1", "T_TOUCH", "RV0", "RV1", "RV_MAX",
  "RIP_START", "RIP_DUR", "B0", "B1", "BFL", "NB",
  "T_MENU", "MENU_DUR", "T_END", "LAND_S", "FALL_S",
  "clamp01", "easeOut", "easeIO", "birdParam", "computeState",
];

function fail(msg) {
  console.error("extract-canon: " + msg);
  process.exit(1);
}

// Windows checkouts may be CRLF; the transform is defined over LF content.
function readLf(path) {
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

function extractStationBody() {
  const html = readLf(STATION_LAB);
  const m = html.match(/<script>\n([\s\S]*?)<\/script>/);
  if (!m) fail("no <script> block found in station-glass.html");
  const body = m[1];
  const cut = body.indexOf("document.getElementById('station')");
  if (cut < 0) fail("trailing DOM-write anchor not found in station-glass.html");
  return body.slice(0, cut).replace(/\s+$/, "");
}

function buildModule(body) {
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by tools/extract-canon.mjs from docs/battle-prototypes/station-glass.html
// (station v1 canon, LOCKED 2026-07-27 — spec docs/superpowers/specs/2026-07-27-station-glass-design.md).
// DO NOT EDIT. The canon body below this header is verbatim (BUILDING.md §8).
// Regenerate: node tools/extract-canon.mjs   Verify: npm run verify:canon
export function buildStationCanon(idSuffix = "") {
${body}
if (idSuffix) out = out.replace(/fcL|skL|wtL/g, (t) => t + idSuffix);
return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-510 -510 1020 1020" width="100%" height="100%">' + out + "</svg>";
}
`;
}

// Normalize a builder body for the lab-copy drift diff: strip blank lines and
// trailing whitespace so wrapper-shape differences (function vs top-level) don't
// mask or fake real drift.
function normalize(s) {
  return s
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .filter((l) => l !== "")
    .join("\n");
}

function extractDiveStationBody() {
  const html = readLf(DIVE_LAB);
  const m = html.match(/function buildStationString\(\)\{\n([\s\S]*?)\nreturn out;\n\}/);
  if (!m) fail("buildStationString not found in dive-intro.html");
  return m[1];
}

function extractTimelineBody() {
  const html = readLf(DIVE_LAB);
  const m = html.match(/<script id="pure">\n([\s\S]*?)<\/script>/);
  if (!m) fail('no <script id="pure"> block found in dive-intro.html');
  return m[1].replace(/\s+$/, "");
}

// ---- M5 battle extractions (plan 2026-07-28-be1-battle-engine-plan.md §Architecture) ----
//
// Three two-anchor slices, verbatim below their headers. PAL ownership: exactly one
// module (diveTimeline.js) EXPORTS PAL; hero/battlefield slices keep their verbatim
// local `const PAL` and the appended footer re-exports diveTimeline's (legal ES —
// a re-export creates no local binding, so no collision). The PAL-equality guard
// below asserts all four lab palettes stay value-identical.
//
// The boss slice ends BEFORE `function drawCrop`: drawCrop/drawGrid (lab lines
// 622-640) reference PAL/ROWS/COLS from the lab's embedded-hero half, outside the
// slice — they would throw on call. 374-621 is verified self-contained. The lab's
// monolithic stormOf/STORM_* reels ride along inertly (verbatim slice, never
// carved); the renderer composes the swarm from per-bat primitives instead.
//
// The boss lab's embedded hero copy (its first half) is a FROZEN older
// scale-reference — it legitimately predates the Power Through additions and is
// never extracted, so it gets no drift guard (plan pass-2 G4).

const HERO_EXPORTS = [
  "ROWS", "COLS", "BX", "buildFrame",
  "IDLE", "ATK", "ATK_MS", "flashOf", "tintOf", "overlay",
  "BUFF", "BUFF_MS", "SLUMP", "SLUMP_DEEP", "DEBUFF", "DEBUFF_MS",
  "CAST", "CAST_MS", "PWR_WIND", "PWR_CRASH", "PWR", "PWR_MS",
  "FAN_SLASH", "FAN", "FAN_MS", "ringPts", "RBK_BASE", "RBK", "RBK_MS",
  "ROOT_THRUST", "ROOT", "ROOT_MS", "goldHairOf",
  "CONV_GRIP", "CONV_GOLD0", "CONV_GOLD1", "CONV", "CONV_MS",
  "HIT_RECOIL", "HIT", "HIT_MS", "KO", "KO_MS", "drawGrid",
];

const BOSS_EXPORTS = [
  "EROWS", "ECOLS", "newG", "eP", "eR", "eCarve", "eOutline",
  "SWARM", "REAL_I", "bellImp", "bellPost", "signImp", "signPost",
  "batImp", "batPost", "swarmOf", "OPT_A", "OPT_B", "OPT_C",
  "batFinal", "batFinalPost", "stormOf", "HIDDEN", "SCREAM", "STORM_REEL",
  "soloBat", "SOLO_STITCH", "SOLO_HOLLOW", "SOLO_RED",
  "eOverlay", "eFlashOf", "eDitherAll", "screamRipple",
  "STORM_ATK", "JIT", "stormJitterOf", "STORM_HIT",
  "stormFallOf", "stormAshes", "STORM_DIE",
];

const BF_EXPORTS = [
  "SR", "SC", "FEET", "BOSS_AT", "HERO_AT", "DCX", "DCY", "DA", "DB", "SAFE",
  "mk", "fillR", "hl", "vl", "dot", "stamp", "hsh", "uOf", "inDisc", "inSafe",
  "secOf", "ringOf", "buildBase", "glassMap", "isGlass",
  "varAS", "varCC", "varSF", "corruptGlass", "glitchScene", "varIS", "erosionStage",
];

// Two-anchor slice; the cut lands at the START of the line holding endAnchor.
function sliceBetween(html, startAnchor, endAnchor, name) {
  const a = html.indexOf(startAnchor);
  if (a < 0) fail("start anchor `" + startAnchor + "` not found in " + name);
  let b = html.indexOf(endAnchor, a);
  if (b < 0) fail("end anchor `" + endAnchor + "` not found in " + name);
  b = html.lastIndexOf("\n", b) + 1;
  return html.slice(a, b).replace(/\s+$/, "");
}

function battleHeader(source, note) {
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by tools/extract-canon.mjs from docs/battle-prototypes/${source}
// (M5 battle canon — plan docs/superpowers/specs/2026-07-28-be1-battle-engine-plan.md).
// DO NOT EDIT. The slice below this header is verbatim (BUILDING.md §9).
// ${note}
// Regenerate: node tools/extract-canon.mjs   Verify: npm run verify:canon
`;
}

function buildHeroModule(body) {
  return battleHeader("hero-battle.html", "Conviction/Rollback/Root-Cause reels ship inertly; only the starting kit is wired in M5.") +
    body + "\n" +
    "export { " + HERO_EXPORTS.join(", ") + " };\n" +
    'export { PAL } from "./diveTimeline.js";\n';
}

function buildBossModule(body) {
  return battleHeader("boss-alert-storm.html", "Per-bat primitives are the API; monolithic storm reels ride along inertly. No PAL here — import it from diveTimeline.") +
    body + "\n" +
    "export { " + BOSS_EXPORTS.join(", ") + " };\n";
}

function buildBfModule(body) {
  return battleHeader("battlefield.html", "Scene builders + varAS corrupted arena; SPR/compose excluded — the renderer owns actor placement.") +
    body + "\n" +
    "export { " + BF_EXPORTS.join(", ") + " };\n" +
    'export { PAL } from "./diveTimeline.js";\n';
}

// PAL-equality guard (pass-1 F13 / pass-2 n1): parse each lab's PAL literal and
// deep-compare VALUES (text differs legitimately: quoting/layout).
function parsePal(html, name) {
  const m = html.match(/const PAL = (\{[\s\S]*?\});/);
  if (!m) fail("PAL literal not found in " + name);
  return new Function("return " + m[1])();
}

function canonicalJson(obj) {
  return JSON.stringify(obj, Object.keys(obj).sort());
}

function buildTimelineModule(tbody) {
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by tools/extract-canon.mjs from docs/battle-prototypes/dive-intro.html
// (<script id="pure"> — the Dive to the Heart pure timeline, approved 2026-07-28,
// spec docs/superpowers/specs/2026-07-28-dive-intro-design.md).
// DO NOT EDIT. The block below this header is verbatim (BUILDING.md §8/§9).
// Regenerate: node tools/extract-canon.mjs   Verify: npm run verify:canon
${tbody}
export { ${TIMELINE_EXPORTS.join(", ")} };
`;
}

const body = extractStationBody();
const generated = buildModule(body);
const timelineBody = extractTimelineBody();
const generatedTimeline = buildTimelineModule(timelineBody);

const heroHtml = readLf(HERO_LAB);
const bossHtml = readLf(BOSS_LAB);
const bfHtml = readLf(BF_LAB);
const generatedHero = buildHeroModule(
  sliceBetween(heroHtml, "const PAL", "document.getElementById('staticRow')", "hero-battle.html"),
);
const generatedBoss = buildBossModule(
  sliceBetween(bossHtml, "const EROWS", "function drawCrop", "boss-alert-storm.html"),
);
const generatedBf = buildBfModule(
  sliceBetween(bfHtml, "const PAL", "const BUILDERS", "battlefield.html"),
);

// Drift guard first — the lab's embedded copy must match canon regardless of mode.
const diveBody = extractDiveStationBody();
if (normalize(diveBody) !== normalize(body)) {
  fail("DRIFT: dive-intro.html's embedded station copy no longer matches station-glass.html canon");
}

// PAL-equality guard: all four lab palettes must stay value-identical
// (diveTimeline.js — the one exporter — is itself byte-guarded against dive-intro.html).
const palRef = canonicalJson(parsePal(readLf(DIVE_LAB), "dive-intro.html"));
for (const [html, name] of [
  [heroHtml, "hero-battle.html"],
  [bossHtml, "boss-alert-storm.html"],
  [bfHtml, "battlefield.html"],
]) {
  if (canonicalJson(parsePal(html, name)) !== palRef) {
    fail("DRIFT: PAL in " + name + " no longer value-matches dive-intro.html's palette");
  }
}

if (process.argv.includes("--verify")) {
  const targets = [
    [OUT_JS, generated, "stationCanon.js"],
    [OUT_TIMELINE, generatedTimeline, "diveTimeline.js"],
    [OUT_HERO, generatedHero, "heroBattle.js"],
    [OUT_BOSS, generatedBoss, "bossAlertStorm.js"],
    [OUT_BF, generatedBf, "battlefieldScene.js"],
  ];
  for (const [path, fresh, name] of targets) {
    let committed;
    try {
      committed = readLf(path);
    } catch {
      fail("src/generated/" + name + " missing — run: node tools/extract-canon.mjs");
    }
    if (committed !== fresh) fail("DRIFT: committed " + name + " differs from a fresh extraction");
  }
  console.log("verify:canon OK — station/timeline/hero/boss/battlefield modules match canon; lab station copy + PAL values match");
} else {
  mkdirSync(dirname(OUT_JS), { recursive: true });
  writeFileSync(OUT_JS, generated);
  writeFileSync(OUT_TIMELINE, generatedTimeline);
  writeFileSync(OUT_HERO, generatedHero);
  writeFileSync(OUT_BOSS, generatedBoss);
  writeFileSync(OUT_BF, generatedBf);
  console.log(
    "extract-canon: wrote stationCanon.js (" + generated.length + " b) + diveTimeline.js (" + generatedTimeline.length +
    " b) + heroBattle.js (" + generatedHero.length + " b) + bossAlertStorm.js (" + generatedBoss.length +
    " b) + battlefieldScene.js (" + generatedBf.length + " b)",
  );
}
